# Generated by Django 3.2.11 on 2022-02-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fight',
            new_name='Flight',
        ),
    ]
